# Generated by Django 2.1.7 on 2019-05-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_from_HR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_from_evaluation_committee',
            field=models.BooleanField(default=False),
        ),
    ]
