# Generated by Django 2.1.7 on 2019-03-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='code',
            field=models.CharField(max_length=200),
        ),
    ]
