# Generated by Django 2.1.7 on 2019-05-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190515_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
    ]
