# Generated by Django 2.1.7 on 2019-03-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190304_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='one_time_use_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
