# Generated by Django 2.1.7 on 2019-04-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
