# Generated by Django 2.1.7 on 2019-03-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registrant_is_code_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='code_used',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
