# Generated by Django 2.1.7 on 2019-05-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190503_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
