# Generated by Django 2.1.7 on 2019-05-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_hrassessment_hrassessmentregistrant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HRAssessment',
        ),
        migrations.RemoveField(
            model_name='hrassessmentregistrant',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='hrassessmentregistrant',
            name='registrant',
        ),
        migrations.DeleteModel(
            name='HRAssessmentRegistrant',
        ),
    ]
