# Generated by Django 2.1.7 on 2019-05-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190507_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
