# Generated by Django 2.1.7 on 2019-04-05 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_location_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackItemAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=255)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_item', to='events.Track')),
            ],
            options={
                'verbose_name': 'Agenda item',
                'verbose_name_plural': 'Agenda items',
                'ordering': ['time'],
            },
        ),
    ]
