# Generated by Django 2.1.7 on 2019-05-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_attendance_max_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackitemagenda',
            name='time',
            field=models.CharField(max_length=25),
        ),
    ]
