# Generated by Django 2.1.7 on 2019-09-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190910_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='title',
        ),
    ]
