# Generated by Django 2.1.7 on 2019-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20190917_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='registrant',
            unique_together={('email', 'event')},
        ),
    ]
