# Generated by Django 2.2.10 on 2020-03-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200223_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
