# Generated by Django 2.1.7 on 2019-09-10 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_auto_20190910_1220'),
        ('assessments', '0002_teamassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAssessmentResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Assessment')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Team')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='teamassessmentresults',
            unique_together={('assessment', 'team', 'evaluator')},
        ),
    ]
