# Generated by Django 2.1.7 on 2019-09-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_auto_20190910_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamassessmentresults',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'team assessment results'},
        ),
    ]
