# Generated by Django 2.1.7 on 2019-09-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_auto_20190911_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamassessment',
            old_name='is_evaluated',
            new_name='has_been_assessed',
        ),
    ]
