# Generated by Django 2.2.10 on 2020-04-30 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_evaluation_last_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='evaluation_committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_committee', to='online.EvaluationCommittee'),
        ),
    ]
