# Generated by Django 2.2.10 on 2020-05-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_auto_20200507_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='committee_score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='jury_score',
        ),
    ]
