# Generated by Django 2.2.10 on 2020-05-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0008_auto_20200509_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryscore',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_score', to='online.Evaluation'),
        ),
    ]
