# Generated by Django 2.2.10 on 2020-05-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0010_auto_20200514_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFinalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='online.Team')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
