# Generated by Django 2.2.10 on 2020-05-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0011_teamfinalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='fullname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
