# Generated by Django 2.2.10 on 2020-05-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0012_auto_20200520_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='evaluation_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_committee', to='online.EvaluationCommittee'),
        ),
    ]
