# Generated by Django 2.1.7 on 2019-04-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('is_valid', models.BooleanField(default=False)),
                ('max_number_of_participants', models.PositiveIntegerField(default=8)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_idea', to='events.Registrant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_idea', to='events.Event')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='IdeaTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_team_member', to='ideas.Idea')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_idea', to='events.Registrant')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Groups',
                'ordering': ['idea'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ideateammember',
            unique_together={('idea', 'member')},
        ),
    ]
