# Generated by Django 2.1.7 on 2019-05-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_juryassessment_juryassessmentidea_moderatorassessment_moderatorassessmentidea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeratorAssessment',
        ),
        migrations.RemoveField(
            model_name='moderatorassessmentidea',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='moderatorassessmentidea',
            name='moderator',
        ),
        migrations.DeleteModel(
            name='ModeratorAssessmentIdea',
        ),
    ]
