# Generated by Django 2.1.7 on 2019-05-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20190507_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juryassessment',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='juryassessment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
