# Generated by Django 2.1.7 on 2019-05-07 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20190507_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JuryAssessment',
        ),
        migrations.RemoveField(
            model_name='juryassessmentidea',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='juryassessmentidea',
            name='jury',
        ),
        migrations.DeleteModel(
            name='JuryAssessmentIdea',
        ),
    ]
