# Generated by Django 2.1.7 on 2019-05-12 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_auto_20190511_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_idea', to='events.Registrant'),
        ),
    ]
