# Generated by Django 2.1.7 on 2019-05-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_auto_20190512_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='max_number_of_participants',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
