# Generated by Django 2.1.7 on 2019-05-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_auto_20190512_0052'),
        ('ideas', '0006_auto_20190507_2351'),
    ]

    operations = [
    ]
