# Generated by Django 2.1.7 on 2019-05-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_merge_20190515_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
