# Generated by Django 2.1.7 on 2019-09-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_idea_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_idea', to='events.Event'),
        ),
    ]
